"""Switch the generated Android release build from the debug key to the
upload keystore provided through GitHub secrets.

Usage: python3 tool/ci/configure_android_signing.py android/app/build.gradle

The keystore path and passwords are read from environment variables at build
time (ANDROID_KEYSTORE_PATH, ANDROID_KEYSTORE_PASSWORD, ANDROID_KEY_ALIAS,
ANDROID_KEY_PASSWORD), so no secret is written into the project files.
"""
import pathlib
import re
import sys

SIGNING_BLOCK = '''
    signingConfigs {
        release {
            storeFile file(System.getenv("ANDROID_KEYSTORE_PATH"))
            storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
            keyAlias System.getenv("ANDROID_KEY_ALIAS")
            keyPassword System.getenv("ANDROID_KEY_PASSWORD")
        }
    }

    buildTypes {'''


def main() -> None:
    path = pathlib.Path(sys.argv[1])
    if not path.exists():
        sys.exit(f"::error::{path} not found (only the Groovy build.gradle generated by Flutter 3.22 is supported)")

    text = path.read_text()
    if "signingConfigs {" not in text:
        text, count = re.subn(r"\n\s*buildTypes\s*\{", SIGNING_BLOCK, text, count=1)
        if count != 1:
            sys.exit("::error::Could not find the buildTypes block in build.gradle")

    text, count = re.subn(r"signingConfig\s*=?\s*signingConfigs\.debug", "signingConfig = signingConfigs.release", text)
    if count == 0 and "signingConfigs.release" not in text:
        sys.exit("::error::Could not find the release signingConfig line in build.gradle")

    path.write_text(text)
    print("Release signing configured with the upload keystore.")


if __name__ == "__main__":
    main()
